spring:
  application:
    name: market

  jpa:
    hibernate:
      ddl-auto: none # liquidBase
    open-in-view: false
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

api:
  svc-catalog:
    url: http://market-catalog-ms-service.market.svc.cluster.local/svc/